
import static java.awt.SystemColor.text;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Kitai-sama
 */
public class FrmMain extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMain.class.getName());

    /**
     * Creates new form FrmCaesar
     */
    public FrmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jTextField1 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnmahoa = new javax.swing.JButton();
        btngiaima = new javax.swing.JButton();
        txtmahoa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtkhoa = new javax.swing.JTextField();
        txtvanban = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnmahoaVeg = new javax.swing.JButton();
        btngiaimaVeg = new javax.swing.JButton();
        txtmahoaVeg = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtkhoaVeg = new javax.swing.JTextField();
        txtvanbanVeg = new javax.swing.JTextField();
        btnRandomKey = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnmahoa.setText("Mã Hóa");
        btnmahoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmahoaActionPerformed(evt);
            }
        });

        btngiaima.setText("Giải Mã ");
        btngiaima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngiaimaActionPerformed(evt);
            }
        });

        jLabel2.setText("Văn Bản : ");

        jLabel3.setText("Khóa :");

        jLabel4.setText("Mã Hóa :");

        txtvanban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvanbanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtvanban, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmahoa, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtkhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnmahoa)
                            .addComponent(btngiaima))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtvanban, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtkhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnmahoa)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtmahoa, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btngiaima)
                .addGap(0, 100, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Caesar", jPanel1);

        btnmahoaVeg.setText("Mã Hóa");
        btnmahoaVeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmahoaVegActionPerformed(evt);
            }
        });

        btngiaimaVeg.setText("Giải Mã ");
        btngiaimaVeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngiaimaVegActionPerformed(evt);
            }
        });

        txtmahoaVeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmahoaVegActionPerformed(evt);
            }
        });

        jLabel5.setText("Văn Bản : ");

        jLabel6.setText("Khóa :");

        jLabel7.setText("Bản Mã :");

        txtvanbanVeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvanbanVegActionPerformed(evt);
            }
        });

        btnRandomKey.setText("Random Key");
        btnRandomKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRandomKeyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtvanbanVeg, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtkhoaVeg, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRandomKey))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btngiaimaVeg)
                                .addGap(29, 29, 29)
                                .addComponent(btnmahoaVeg))
                            .addComponent(txtmahoaVeg, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtvanbanVeg, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtkhoaVeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRandomKey))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtmahoaVeg, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btngiaimaVeg)
                    .addComponent(btnmahoaVeg))
                .addGap(0, 110, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Vigenere", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Caesar
// Phương thức Mã Hóa từng ký tự với khóa K
char mahoakt(char c, int k)
{
    // Kiểm tra ký tự có phải chữ cái không?
    if (!Character.isLetter(c)) return c;
    return (char) ((((Character.toUpperCase(c) - 'A') +k) % 26 +26 )%26 +'A');
}
// Mã hóa văn bản truyền vào với khóa K
private String mahoa(String br, int k)
{
    String kq = ""; //Lưu Giá trị kết quả sau khi mã hóa
    int n = br.length();
    for(int i =0; i< n; i++)
        kq+= mahoakt(br.charAt(i),k);
                return kq;      
}
    private void btnmahoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmahoaActionPerformed
        // TODO add your handling code here:
                if(txtkhoa.getText().equals("")== true)
                    JOptionPane.showMessageDialog(null,"Vui lòng nhập khóa, Làm ơn!!!");
        else 
        {
            int k = Integer.valueOf(this.txtkhoa.getText());
            String br = this.txtvanban.getText();
            this.txtmahoa.setText(mahoa(br,k));
        }                          
    }//GEN-LAST:event_btnmahoaActionPerformed

    private void txtvanbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvanbanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvanbanActionPerformed

    private void btngiaimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngiaimaActionPerformed
        // TODO add your handling code here:
        int k =Integer.valueOf(this.txtkhoa.getText());
        String br = this.txtmahoa.getText();
        this.txtvanban.setText(mahoa(br,-k));      
    }//GEN-LAST:event_btngiaimaActionPerformed
    
    // Vigenere
    private void btnmahoaVegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmahoaVegActionPerformed
        // TODO add your handling code here:
         // Lấy dữ liệu từ giao diện
    String text = txtvanbanVeg.getText().toUpperCase();
    String key = txtkhoaVeg.getText().toUpperCase();
    StringBuilder result = new StringBuilder();
    
    // Nếu người dùng chưa nhập đủ
    if (text.isEmpty() || key.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập văn bản và khóa!");
        return;
    }
    
      // Biến đếm vị trí ký tự khóa
    int keyIndex = 0;

    // Vòng lặp từng ký tự
    for (int i = 0; i < text.length(); i++) {
        char c = text.charAt(i);
        if (Character.isLetter(c)) {
            // Mã hóa theo Vigenère
            int shift = key.charAt(keyIndex) - 'A';
            char encryptedChar = (char) (((c - 'A' + shift) % 26) + 'A');
            result.append(encryptedChar);

            // Dịch vị trí khóa
            keyIndex = (keyIndex + 1) % key.length();
        } else {
            result.append(c);
        }
    }
        // Hiển thị kết quả ra ô kết quả
    txtmahoaVeg.setText(result.toString());
    }//GEN-LAST:event_btnmahoaVegActionPerformed

    private void btngiaimaVegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngiaimaVegActionPerformed
        // TODO add your handling code here:
    // Lấy dữ liệu từ giao diện
    String text = txtmahoaVeg.getText().toUpperCase();
    String key = txtkhoaVeg.getText().toUpperCase();
    StringBuilder result = new StringBuilder();

    // Kiểm tra nếu thiếu dữ liệu
    if (text.isEmpty() || key.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập văn bản và khóa!");
        return;
    }

    int keyIndex = 0;

    // Vòng lặp giải mã từng ký tự
    for (int i = 0; i < text.length(); i++) {
        char c = text.charAt(i);
        if (Character.isLetter(c)) {
            int shift = key.charAt(keyIndex) - 'A';
            char decryptedChar = (char) (((c - 'A' - shift + 26) % 26) + 'A');
            result.append(decryptedChar);
            keyIndex = (keyIndex + 1) % key.length();
        } else {
            result.append(c);
        }
    }

    // Hiển thị kết quả ra ô kết quả
    txtvanbanVeg.setText(result.toString());
    }//GEN-LAST:event_btngiaimaVegActionPerformed

    private void txtvanbanVegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvanbanVegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvanbanVegActionPerformed

    private void txtmahoaVegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmahoaVegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmahoaVegActionPerformed

    private void btnRandomKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRandomKeyActionPerformed
        // TODO add your handling code here:
            // Độ dài khóa ngẫu nhiên (5–10 ký tự)
    int length = (int)(Math.random() * 6) + 5;  // từ 5 đến 10
    StringBuilder randomKey = new StringBuilder();

    // Sinh các ký tự A–Z ngẫu nhiên
    for (int i = 0; i < length; i++) {
        char randomChar = (char) ('A' + (int)(Math.random() * 26));
        randomKey.append(randomChar);
    }

    // Hiển thị vào ô nhập khóa
    txtkhoaVeg.setText(randomKey.toString());
        
    }//GEN-LAST:event_btnRandomKeyActionPerformed

    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMain().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRandomKey;
    private javax.swing.JButton btngiaima;
    private javax.swing.JButton btngiaimaVeg;
    private javax.swing.JButton btnmahoa;
    private javax.swing.JButton btnmahoaVeg;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtkhoa;
    private javax.swing.JTextField txtkhoaVeg;
    private javax.swing.JTextField txtmahoa;
    private javax.swing.JTextField txtmahoaVeg;
    private javax.swing.JTextField txtvanban;
    private javax.swing.JTextField txtvanbanVeg;
    // End of variables declaration//GEN-END:variables
}
